import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.text.Text;

public class QuizzesController {

    @FXML
    private Button gradesbtn;

    @FXML
    private Button homeBtn;

    @FXML
    private Button logoutbtn;

    @FXML
    private Button quizBtn1;

    @FXML
    private Button quizBtn2;

    @FXML
    private Button quizBtn3;

    @FXML
    private Button quizzesbtn;

    @FXML
    private Text text1;

    @FXML
    private Text text2;

    @FXML
    private Text text3;

    @FXML
    private Label userLbl;

    @FXML
    private Label welcomeLbl;

    @FXML
    void logout(ActionEvent event) {

    }

}
